In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

print("Ready")

Ready

In [2]:
DATA_PATH = (
    "../data/"
    "marketing_sample_for_amazon_com-amazon_fashion_products__20200201_20200430__30k_data.ldjson"
)

df = pd.read_json(DATA_PATH, lines=True)

print(df.shape)
df.head()

(30000, 33)

,uniq_id,crawl_timestamp,asin,product_url,product_name,image_urls__small,medium,large,browsenode,brand,sales_price,weight,rating,sales_rank_in_parent_category,sales_rank_in_child_category,delivery_type,meta_keywords,amazon_prime__y_or_n,parent___child_category__all,best_seller_tag__y_or_n,other_items_customers_buy,product_details__k_v_pairs,discount_percentage,colour,no__of_reviews,seller_name,seller_id,left_in_stock,no__of_offers,no__of_sellers,technical_details__k_v_pairs,formats___editions,name_of_author_for_books
0,26d41bdc1495de290bc8e6062d927729,2020-02-07 05:11:36 +0000,B07STS2W9T,https://www.amazon.in/Facon-Kalamkari-Handblock-Dancers-Lehenga/dp/B07SWVSRPP/,LA' Facon Cotton Kalamkari Handblock Saree Blouse Fabric 100 cms Black Base Dancers (Cotton),"https://images-na.ssl-images-amazon.com/images/I/51Wj2WownyL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/51tylkSxAIL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...",https://images-na.ssl-images-amazon.com/images/I/51Wj2WownyL.jpg|https://images-na.ssl-images-amazon.com/images/I/51tylkSxAIL.jpg|https://images-na.ssl-images-amazon.com/images/I/51345gshQ9L.jpg,https://images-na.ssl-images-amazon.com/images/I/81MqmouZ9kL._UL1500_.jpg|https://images-na.ssl-images-amazon.com/images/I/814Tnuvt5kL._UL1500_.jpg|https://images-na.ssl-images-amazon.com/images/I...,1.968255e+09,LA' Facon,200.0,999999999,5.0,"{'ClothingAccessories': '#19,259'}",{'WomensKurtasKurtis': '#1793'},fulfilled_by_merchant,LA' Facon Cotton Kalamkari Handblock Saree Blouse Fabric 100 cms Black Base Dancers (Cotton),N,"{'ClothingAccessories': '#19,259', 'WomensKurtasKurtis': '#1793'}",N,Cotton Kalamkari Handblock Saree Blouse/Kurti Fabric 100 cms - Base Dancer Print - Red Colour | RJFabrics Women's Printed Cotton Fabric (2.5 Meter Length 43 Inch Width) | Cotton Kalamkari Handbloc...,"{'Item_part_number': 'Devi face', 'ASIN': 'B07STS2W9T', 'Date_first_available_at_Amazon_in': '8 June 2019', 'Customer_Reviews': '5.0 out of 5 stars 3 customer reviews', 'Amazon_Bestsellers_Rank': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,410c62298852e68f34c35560f2311e5a,2020-02-07 08:45:56 +0000,B07N6TD2WL,https://www.amazon.in/Sf-Jeans-Pantaloons-T-Shirt-110048418_Blue_Xx-Large/dp/B07N4DD8S3/,Sf Jeans By Pantaloons Men's Plain Slim fit T-Shirt,"https://images-na.ssl-images-amazon.com/images/I/41fqj9cvevL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/41gTOgKzJpL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...",https://images-na.ssl-images-amazon.com/images/I/41fqj9cvevL.jpg|https://images-na.ssl-images-amazon.com/images/I/41gTOgKzJpL.jpg|https://images-na.ssl-images-amazon.com/images/I/41CZ2wta57L.jpg|h...,https://images-na.ssl-images-amazon.com/images/I/81LH9iUG-8L._UL1500_.jpg|https://images-na.ssl-images-amazon.com/images/I/814-uRHcmNL._UL1500_.jpg|https://images-na.ssl-images-amazon.com/images/I...,1.968123e+09,NaN,265.0,999999999,3.6,"{'ClothingAccessories': '#1,59,062'}",{'MensT_Shirts': '#12151'},fulfilled_by_merchant,"Sf Jeans By Pantaloons Men's Plain Slim fit T-Shirt,Aditya Birla Fashion & Retail Ltd",N,"{'ClothingAccessories': '#1,59,062', 'MensT_Shirts': '#12151'}",N,Sf Jeans By Pantaloons Men's Slim fit T-Shirt | Urban Ranger by Pantaloons Men's Slim fit T-Shirt | Urban Ranger by Pantaloons Men's Tribal Slim Fit T-Shirt | Sf Jeans By Pantaloons Men's Slim fit...,"{'ASIN': 'B07N6TD2WL', 'Date_first_available_at_Amazon_in': '28 January 2019', 'Customer_Reviews': '3.0 out of 5 stars 3 customer reviews', 'Amazon_Bestsellers_Rank': '#1,59,062 in Clothing & Acce...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,52e31bb31680b0ec73de0d781a23cc0a,2020-02-06 11:09:38 +0000,B07WJ6WPN1,https://www.amazon.in/LOVISTA-Traditional-Printed-Angrakha-Turquoise/dp/B07WH3SH25/,"LOVISTA Cotton Gota Patti Tassel Traditional Printed Kurti with Pant,Angrakha Salwar Suit","https://images-na.ssl-images-amazon.com/images/I/31Gd40UmBTL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/31jiPD9IyQL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...",https://images-na.ssl-images-amazon.com/images/I/31Gd40UmBTL.jpg|https://images-na.ssl-images-amazon.com/images/I/31jiPD9IyQL.jpg|https://images-na.ssl-images-amazon.com/images/I/41GLhLnUCGL.jpg,https://images-na.ssl-images-amazon.com/images/I/614BleyPAFL._UL1280_.jpg|https://images-na.ssl-images-amazon.com/images/I/61mWeZbi08L._UL1280_.jpg|https://images-na.ssl-images-amazon.com/images/I...,1.968255e+09,LOVISTA,660.0,999999999,3.5,"{'ClothingAccessories': '#1,050'}",{'WomensKurtasKurtis': '#91'},fulfilled_by_merchant,"LOVISTA Cotton Gota Patti Tassel Traditional Printed Kurti with Pant,Angrakha Salwar Suit,LOVISTA",Y,"{'ClothingAccessories': '#1,050', 'WomensKurtasKurtis': '#91'}",N,"Stylum Women's Cotton Floral Print Straight kurta Pant and Dupatta Set | Khushal K Women's Cotton Kurta With Palazzo Set (Light Pink) | Bae's Wardrobe Women's Rayon Printed A Line Kurti, Palazo Pa...","{'Item_part_number': 'KUM-011', 'ASIN': 'B07WJ6WPN1', 'Date_first_available_at_Amazon_in': '16 August 2019', 'Customer_Reviews': '3.7 out of 5 stars 23 customer reviews', 'Amazon_Bestsellers_Rank'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25798d6dc43239c118452d1bee0fb088,2020-02-07 08:32:45 +0000,B07PYSF4WZ,https://www.amazon.in/People-Printed-Regular-T-Shirt-P1C109318URB219_Blue_Medium/dp/B07PN5X147/,People Men's Printed Regular fit T-Shirt,"https://images-na.ssl-images-amazon.com/images/I/41O5j3l3ofL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/41VgvZ4QnvL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...",https://images-na.ssl-images-amazon.com/images/I/41O5j3l3ofL.jpg|https://images-na.ssl-images-amazon.com/images/I/41VgvZ4QnvL.jpg|https://images-na.ssl-images-amazon.com/images/I/51EGl11EsJL.jpg|h...,https://images-na.ssl-images-amazon.com/images/I/91NwCUxcFXL._UL1500_.jpg|https://images-na.ssl-images-amazon.com/images/I/91iAuw5G8fL._UL1500_.jpg|https://images-na.ssl-images-amazon.com/images/I...,1.968123e+09,NaN,195.0,999999999,3.0,"{'ClothingAccessories': '#2,47,234'}",{'MensT_Shirts': '#19368'},fulfilled_by_merchant,"People Men's Printed Regular fit T-Shirt,People",N,"{'ClothingAccessories': '#2,47,234', 'MensT_Shirts': '#19368'}",N,People Men's Printed Regular Fit T-Shirt | Lee Cooper Men's Regular fit T-Shirt | People Men's Plain Regular Fit T-Shirt | People Men's Regular fit T-Shirt,"{'ASIN': 'B07PYSF4WZ', 'Date_first_available_at_Amazon_in': '21 March 2019', 'Customer_Reviews': '3.0 out of 5 stars 1 customer review', 'Amazon_Bestsellers_Rank': '#2,47,234 in Clothing & Accesso...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ad8a5a196d515ef09dfdaf082bdc37c4,2020-02-06 14:27:48 +0000,B082KXNM7X,https://www.amazon.in/Monte-Carlo-Cotton-Collar-Tracksuit/dp/B082KXRQSZ/,Monte Carlo Grey Solid Cotton Blend Polo Collar Tracksuit,"https://images-na.ssl-images-amazon.com/images/I/31UYeJhMAbL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/31JxfBshZbL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...",https://images-na.ssl-images-amazon.com/images/I/31UYeJhMAbL.jpg|https://images-na.ssl-images-amazon.com/images/I/31JxfBshZbL.jpg|https://images-na.ssl-images-amazon.com/images/I/314fs0OwGzL.jpg|h...,https://images-na.ssl-images-amazon.com/images/I/61F0N7uUiLL._UL1500_.jpg|https://images-na.ssl-images-amazon.com/images/I/61K0oYhFa4L._UL1500_.jpg|https://images-na.ssl-images-amazon.com/images/I...,1.968070e+09,NaN,1914.0,999999999,5.0,"{'ClothingAccessories': '#13,980'}",{'MensTracksuits': '#12'},fulfilled_by_merchant,"Monte Carlo Grey Solid Cotton Blend Polo Collar Tracksuit,Monte Carlo Fashions Limited Unit-2, 231, Industrial Area - A, Ludhiana-141003, Punjab, India",Y,"{'ClothingAccessories': '#13,980', 'MensTracksuits': '#12'}",N,Monte Carlo Grey Solid Cotton Blend Polo Collar Tracksuit | Monte Carlo Black Solid Cotton Blend Polo Collar Tracksuit | Monte Carlo Black Grey Solid Cotton Blend Hood Tracksuit | Monte Carlo Soli...,"{'Item_part_number': 'BBAPLMC154483', 'ASIN': 'B082KXNM7X', 'Date_first_available_at_Amazon_in': '10 December 2019', 'Customer_Reviews': 'Be the first to review this item', 'Amazon_Bestsellers_Ran...",40%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 33 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   uniq_id                        30000 non-null  str
 1   crawl_timestamp                30000 non-null  str
 2   asin                           30000 non-null  str
 3   product_url                    30000 non-null  str
 4   product_name                   30000 non-null  str
 5   image_urls__small              29998 non-null  str
 6   medium                         29998 non-null  str
 7   large                          28841 non-null  str
 8   browsenode                     29480 non-null  float64
 9   brand                          21857 non-null  str
 10  sales_price                    27110 non-null  float64
 11  weight                         30000 non-null  str
 12  rating                         30000 non-null  float64
 13  sales_rank_in_parent_category  25497 non-null  object
 14  sales_rank_in_child_category   24851 non-null  object
 15  delivery_type                  30000 non-null  str
 16  meta_keywords                  30000 non-null  str
 17  amazon_prime__y_or_n           30000 non-null  str
 18  parent___child_category__all   25497 non-null  object
 19  best_seller_tag__y_or_n        30000 non-null  str
 20  other_items_customers_buy      24363 non-null  str
 21  product_details__k_v_pairs     28817 non-null  object
 22  discount_percentage            14624 non-null  str
 23  colour                         6029 non-null   str
 24  no__of_reviews                 3452 non-null   float64
 25  seller_name                    8364 non-null   str
 26  seller_id                      8364 non-null   str
 27  left_in_stock                  3057 non-null   float64
 28  no__of_offers                  1020 non-null   float64
 29  no__of_sellers                 1020 non-null   float64
 30  technical_details__k_v_pairs   1154 non-null   object
 31  formats___editions             2 non-null      str
 32  name_of_author_for_books       1 non-null      str
dtypes: float64(7), object(5), str(21)
memory usage: 7.6+ MB

In [4]:
df.columns.tolist()

['uniq_id',
 'crawl_timestamp',
 'asin',
 'product_url',
 'product_name',
 'image_urls__small',
 'medium',
 'large',
 'browsenode',
 'brand',
 'sales_price',
 'weight',
 'rating',
 'sales_rank_in_parent_category',
 'sales_rank_in_child_category',
 'delivery_type',
 'meta_keywords',
 'amazon_prime__y_or_n',
 'parent___child_category__all',
 'best_seller_tag__y_or_n',
 'other_items_customers_buy',
 'product_details__k_v_pairs',
 'discount_percentage',
 'colour',
 'no__of_reviews',
 'seller_name',
 'seller_id',
 'left_in_stock',
 'no__of_offers',
 'no__of_sellers',
 'technical_details__k_v_pairs',
 'formats___editions',
 'name_of_author_for_books']

In [5]:
missing = (
    df.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing_percent = (
    (missing / len(df)) * 100
).round(2)

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_percent
})

missing_df.head(30)

                               missing_count  missing_percent
name_of_author_for_books               29999           100.00
formats___editions                     29998            99.99
no__of_sellers                         28980            96.60
no__of_offers                          28980            96.60
technical_details__k_v_pairs           28846            96.15
left_in_stock                          26943            89.81
no__of_reviews                         26548            88.49
colour                                 23971            79.90
seller_id                              21636            72.12
seller_name                            21636            72.12
discount_percentage                    15376            51.25
brand                                   8143            27.14
other_items_customers_buy               5637            18.79
sales_rank_in_child_category            5149            17.16
parent___child_category__all            4503            15.01
sales_rank_in_parent_category           4503            15.01
sales_price                             2890             9.63
product_details__k_v_pairs              1183             3.94
large                                   1159             3.86
browsenode                               520             1.73
image_urls__small                          2             0.01
medium                                     2             0.01
uniq_id                                    0             0.00
best_seller_tag__y_or_n                    0             0.00
amazon_prime__y_or_n                       0             0.00
crawl_timestamp                            0             0.00
delivery_type                              0             0.00
rating                                     0             0.00
weight                                     0             0.00
product_name                               0             0.00

In [6]:
candidate_columns = [
    "uniq_id",
    "product_name",
    "brand",
    "colour",
    "sales_price",
    "weight",
    "rating",
    "image_urls__small",
    "meta_keywords",
    "product_details__k_v_pairs",
    "parent___child_category__all",
]

df[candidate_columns].head(10)

,uniq_id,product_name,brand,colour,sales_price,weight,rating,image_urls__small,meta_keywords,product_details__k_v_pairs,parent___child_category__all
0,26d41bdc1495de290bc8e6062d927729,LA' Facon Cotton Kalamkari Handblock Saree Blouse Fabric 100 cms Black Base Dancers (Cotton),LA' Facon,NaN,200.0,999999999,5.0,"https://images-na.ssl-images-amazon.com/images/I/51Wj2WownyL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/51tylkSxAIL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...",LA' Facon Cotton Kalamkari Handblock Saree Blouse Fabric 100 cms Black Base Dancers (Cotton),"{'Item_part_number': 'Devi face', 'ASIN': 'B07STS2W9T', 'Date_first_available_at_Amazon_in': '8 June 2019', 'Customer_Reviews': '5.0 out of 5 stars 3 customer reviews', 'Amazon_Bestsellers_Rank': ...","{'ClothingAccessories': '#19,259', 'WomensKurtasKurtis': '#1793'}"
1,410c62298852e68f34c35560f2311e5a,Sf Jeans By Pantaloons Men's Plain Slim fit T-Shirt,NaN,NaN,265.0,999999999,3.6,"https://images-na.ssl-images-amazon.com/images/I/41fqj9cvevL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/41gTOgKzJpL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...","Sf Jeans By Pantaloons Men's Plain Slim fit T-Shirt,Aditya Birla Fashion & Retail Ltd","{'ASIN': 'B07N6TD2WL', 'Date_first_available_at_Amazon_in': '28 January 2019', 'Customer_Reviews': '3.0 out of 5 stars 3 customer reviews', 'Amazon_Bestsellers_Rank': '#1,59,062 in Clothing & Acce...","{'ClothingAccessories': '#1,59,062', 'MensT_Shirts': '#12151'}"
2,52e31bb31680b0ec73de0d781a23cc0a,"LOVISTA Cotton Gota Patti Tassel Traditional Printed Kurti with Pant,Angrakha Salwar Suit",LOVISTA,NaN,660.0,999999999,3.5,"https://images-na.ssl-images-amazon.com/images/I/31Gd40UmBTL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/31jiPD9IyQL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...","LOVISTA Cotton Gota Patti Tassel Traditional Printed Kurti with Pant,Angrakha Salwar Suit,LOVISTA","{'Item_part_number': 'KUM-011', 'ASIN': 'B07WJ6WPN1', 'Date_first_available_at_Amazon_in': '16 August 2019', 'Customer_Reviews': '3.7 out of 5 stars 23 customer reviews', 'Amazon_Bestsellers_Rank'...","{'ClothingAccessories': '#1,050', 'WomensKurtasKurtis': '#91'}"
3,25798d6dc43239c118452d1bee0fb088,People Men's Printed Regular fit T-Shirt,NaN,NaN,195.0,999999999,3.0,"https://images-na.ssl-images-amazon.com/images/I/41O5j3l3ofL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/41VgvZ4QnvL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...","People Men's Printed Regular fit T-Shirt,People","{'ASIN': 'B07PYSF4WZ', 'Date_first_available_at_Amazon_in': '21 March 2019', 'Customer_Reviews': '3.0 out of 5 stars 1 customer review', 'Amazon_Bestsellers_Rank': '#2,47,234 in Clothing & Accesso...","{'ClothingAccessories': '#2,47,234', 'MensT_Shirts': '#19368'}"
4,ad8a5a196d515ef09dfdaf082bdc37c4,Monte Carlo Grey Solid Cotton Blend Polo Collar Tracksuit,NaN,NaN,1914.0,999999999,5.0,"https://images-na.ssl-images-amazon.com/images/I/31UYeJhMAbL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/31JxfBshZbL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...","Monte Carlo Grey Solid Cotton Blend Polo Collar Tracksuit,Monte Carlo Fashions Limited Unit-2, 231, Industrial Area - A, Ludhiana-141003, Punjab, India","{'Item_part_number': 'BBAPLMC154483', 'ASIN': 'B082KXNM7X', 'Date_first_available_at_Amazon_in': '10 December 2019', 'Customer_Reviews': 'Be the first to review this item', 'Amazon_Bestsellers_Ran...","{'ClothingAccessories': '#13,980', 'MensTracksuits': '#12'}"
5,73fd23f631d4434fd4a41ecc1b9f5eed,Forest Club | Gym Wear | Sports Shorts| Shorts for Men | Smooth Breathable Fabric | Shorts with Pocket Zippers | All TIME WEAR |,Forest Club,Black|Blue|Grey,350.0,999999999,4.1,"https://images-na.ssl-images-amazon.com/images/I/417-zhcsWiL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/31OvZrq-V8L._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...",Forest Club | Gym Wear | Sports Shorts| Shorts for Men | Smooth Breathable Fabric | Shorts with Pocket Zippers | All TIME WEAR |,"{'Item_part_number': 'FC_NONLYCRA_PATTI PIPING', 'ASIN': 'B07X5M41BJ', 'Date_first_available_at_Amazon_in': '29 August 2019', 'Customer_Reviews': '4.7 out of 5 stars 4 customer reviews', 'Amazon_B...","{'ClothingAccessories': '#4,399', 'MensShorts': '#30'}"
6,14d7d34c3cacd6c9ed1aa57f284e37ad,PrintOctopus Graphic Printed T-Shirt for Men Chill T-Shirt | Hindi Quote T-Shirt | Half Sleeve T-Shirt for Women | Round Neck T Shirt | 100% Cotton T-Shirt | Short Sleeve T Shirt,PrintOctopus,Black|Navy Blue,288.0,99.8 g,3.7,"https://images-na.ssl-images-amazon.com/images/I/41-t1F0%2BHgL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/41zv8uJZbzL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/imag...","PrintOctopus Graphic Printed T-Shirt for Men Chill T-Shirt | Hindi Quote T-Shirt | Half Sleeve T-Shirt for Women | Round Neck T Shirt | 100% Cotton T-Shirt | Short Sleeve T Shirt,PrintOctopus","{'Product_Dimensions': '10 x 10 x 1 cm ; 99.8 g', 'Item_part_number': 'CL-RN-ChillOut-DUMMY', 'ASIN': 'B07H9RCVHQ', 'Date_first_available_at_Amazon_in': '12 September 2018', 'Customer_Reviews': '3...","{'ClothingAccessories': '#14,838', 'MensT_Shirts': '#817'}"
7,ab393329c3a9370dc4cc89db35fbcd3a,Pepe Jeans Men's Solid Regular fit Casual Shirt,NaN,NaN,919.0,999999999,2.9,"https://images-na.ssl-images-amazon.com/images/I/41M7k32XfeL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/51GihNpO2YL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...","Pepe Jeans Men's Solid Regular fit Casual Shirt,Renaissance Fashions","{'ASIN': 'B07PJ5QWZ3', 'Date_first_available_at_Amazon_in': '8 March 2019', 'Customer_Reviews': '3.5 out of 5 stars 2 customer reviews', 'Amazon_Bestsellers_Rank': '#7,97,407 in Clothing & Accesso...","{'ClothingAccessories': '#7,97,407', 'MensCasualShirts': '#43603'}"
8,2b54891e14ebe52431d753aee2addf1f,Carahere Boys Handmade Pre-Tied Classic Polka Dot Bow Ties M132 Navy Blue,Carahere,NaN,NaN,999999999,4.4,"https://images-na.ssl-images-amazon.com/images/I/41Xf9XxNOeL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/41KHR3Bq7UL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...","Carahere Boys Handmade Pre-Tied Classic Polka Dot Bow Ties M132 Navy Blue,CRHBOWM0O0132-Navy Blue","{'Item_model_number': 'CRHBOWM0O0132-Navy Blue', 'ASIN': 'B01D6VFN7O', 'Date_first_available_at_Amazon_in': '18 October 2017', 'Customer_Reviews': 'Be the first to review this item'}",NaN
9,87540e97ddd999f4986e56d964a6399b,Peppermint Synthetic Dress,Peppermint,NaN,619.0,999999999,5.0,"https://images-na.ssl-images-amazon.com/images/I/41XMF11QpBL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/41gyqTOXvJL._SR38,50_.jpg|https://images-na.ssl-images-amazon.com/images...","Peppermint Synthetic Dress,Peppermint","{'ASIN': 'B07P43X53C', 'Date_first_available_at_Amazon_in': '25 February 2019', 'Customer_Reviews': '5.0 out of 5 stars 1 customer review', 'Amazon_Bestsellers_Rank': '#1,36,237 in Clothing & Acce...","{'ClothingAccessories': '#1,36,237', 'GirlsDressesJumpsuits': '#1820'}"

In [7]:
df["weight"].sample(20)

27573    999999999
26718    999999999
14846    999999999
13361    999999999
28883    999999999
27510    999999999
9164     999999999
29077    999999999
6158     999999999
16638       99.8 g
25024    999999999
17159        299 g
6971     999999999
7059     999999999
29727        227 g
18427        150 g
26891    999999999
29914    999999999
16998    999999999
29350    999999999
Name: weight, dtype: str

In [8]:
print(df["colour"].nunique())
print(df["colour"].value_counts(dropna=False).head(20))

4757
colour
NaN                23971
Black|White           79
Black|Blue            45
Black|Red             34
Black|Navy            31
Blue|Red              30
Black|Navy Blue       21
Blue|Pink             21
Black|Grey            21
White|Black           20
White|Yellow          19
Black|Blue|Red        18
Green|Red             17
Blue|Yellow           15
Pink|Red              15
Brown|Black           15
Blue|Grey             15
Red|Yellow            14
Black|Maroon          12
Black|Pink            12
Name: count, dtype: int64

In [9]:
print(df["brand"].nunique())
print(df["brand"].value_counts(dropna=False).head(20))

6458
brand
NaN                       8143
Max                        504
Generic                    245
BIBA                       205
Mothercare                 156
Campus Sutra               150
Soch                       149
nauti nati                 132
Ada                        127
GRITSTONES                 110
PrintOctopus               102
Allen Solly Junior          93
Columbia                    92
Excalibur by Unlimited      80
Indian Terrain              80
ANNI DESIGNER               78
Buckle Down                 78
MIMOSA                      76
Gini & Jony                 69
Arrow Sports                68
Name: count, dtype: int64

In [10]:
df[[
    "product_name",
    "meta_keywords"
]].sample(10)

,product_name,meta_keywords
20314,"Arise Men’s Half Sleeve Polo Neck Heather T-Shirt, Men's Collar T-Shirt","Arise Men’s Half Sleeve Polo Neck Heather T-Shirt, Men's Collar T-Shirt,Beroe Clothing Company"
22971,Sugr by Unlimited Women's Solid Slim Fit T-Shirt (274384582 Beige L HS),"Sugr by Unlimited Women's Solid Slim Fit T-Shirt (274384582 Beige L HS),Arvind Lifestyle Brands Ltd,274384582 BEIGE L HS"
21746,Kobo Rubber Gymnastic Hand Grips/Cross Pull Up/Gym Gloves for Fitness Functional Training Protector,"Kobo Rubber Gymnastic Hand Grips/Cross Pull Up/Gym Gloves for Fitness Functional Training Protector,Kobo,WTG-18"
14076,Rays Women's Casual Off Shoulder Beige Oat Top,"Rays Women's Casual Off Shoulder Beige Oat Top,Shah International"
13447,Pinaken Men's Round Neck Regular Fit Cotton T-Shirt,"Pinaken Men's Round Neck Regular Fit Cotton T-Shirt,SHARP N INDIA"
6301,Excalibur by Unlimited Men's Solid Regular Fit Formal Shirt (Pack of 2)(Colors & Print May Vary),"Excalibur by Unlimited Men's Solid Regular Fit Formal Shirt (Pack of 2)(400017133300_Assorted_40),Arvind Lifestyle Brands Ltd,400017133300"
9231,Dahlia Mens Cable Wool Blend Beanie Hat - Soft & Warm Velour Lined - Dark Gray,"Dahlia Mens Cable Wool Blend Beanie Hat - Soft & Warm Velour Lined - Dark Gray,HT0113ACM-GY"
26802,BIBA Women's Asymmetrical Hemline Kurta,"BIBA Women's Asymmetrical Hemline Kurta,BIBA Apparels Pvt Ltd,MNMVINTAGE 13611"
26839,Maruti Enterprise Women's Crepe Multi-Coloured Kurti (ME-05 $Parrent SKU),"Maruti Enterprise Women's Crepe Multi-Coloured Kurti (ME-05 $Parrent SKU),Maruti Enterprise"
27579,Jessica Simpson Girls' Two Piece Striped Bikini,"Jessica Simpson Big Girls Two Piece Striped Bikini, Navy, 16,Jessica Simpson (Amerex) Children's Apparel,SP16A04"

In [11]:
df["product_details__k_v_pairs"].iloc[0]

{'Item_part_number': 'Devi face',
 'ASIN': 'B07STS2W9T',
 'Date_first_available_at_Amazon_in': '8 June 2019',
 'Customer_Reviews': '5.0 out of 5 stars 3 customer reviews',
 'Amazon_Bestsellers_Rank': "#19,259 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #1793 in\xa0Women's Kurtas & Kurtis"}

In [12]:
df["product_details__k_v_pairs"].dropna().iloc[0]

{'Item_part_number': 'Devi face',
 'ASIN': 'B07STS2W9T',
 'Date_first_available_at_Amazon_in': '8 June 2019',
 'Customer_Reviews': '5.0 out of 5 stars 3 customer reviews',
 'Amazon_Bestsellers_Rank': "#19,259 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #1793 in\xa0Women's Kurtas & Kurtis"}

In [13]:
feature_missing = df[
    [
        "brand",
        "colour",
        "sales_price",
        "weight",
        "rating",
        "product_name",
        "meta_keywords",
        "parent___child_category__all",
    ]
].isnull().mean().sort_values()

(feature_missing * 100).round(2)

weight                           0.00
rating                           0.00
product_name                     0.00
meta_keywords                    0.00
sales_price                      9.63
parent___child_category__all    15.01
brand                           27.14
colour                          79.90
dtype: float64

In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

/Users/ajaysinghchouhan/Documents/projects/SAP_ML_Engineer_Assesment

In [4]:
from app.services.data_loader import DataLoader
from app.services.preprocessing import (
    ProductPreprocessor
)

loader = DataLoader(
    "../data/marketing_sample_for_amazon_com-amazon_fashion_products__20200201_20200430__30k_data.ldjson"
)

df = loader.load_data()

processor = ProductPreprocessor()

processed_df = processor.preprocess(df)

processed_df[[
    "brand",
    "colour",
    "sales_price",
    "weight",
    "weight_cleaned",
    "combined_text"
]].head()

2026-05-28 18:58:09.343 | INFO     | app.services.data_loader:load_data:21 - Loading dataset from ../data/marketing_sample_for_amazon_com-amazon_fashion_products__20200201_20200430__30k_data.ldjson
2026-05-28 18:58:10.047 | INFO     | app.services.data_loader:load_data:30 - Loaded dataset with shape: (30000, 33)
2026-05-28 18:58:10.048 | INFO     | app.services.preprocessing:preprocess:19 - Starting preprocessing pipeline
2026-05-28 18:58:10.124 | INFO     | app.services.preprocessing:preprocess:35 - Finished preprocessing

,brand,colour,sales_price,weight,weight_cleaned,combined_text
0,la' facon,unknown,200.0,999999999,231.0,LA' Facon Cotton Kalamkari Handblock Saree Blo...
1,unknown,unknown,265.0,999999999,231.0,Sf Jeans By Pantaloons Men's Plain Slim fit T-...
2,lovista,unknown,660.0,999999999,231.0,LOVISTA Cotton Gota Patti Tassel Traditional P...
3,unknown,unknown,195.0,999999999,231.0,People Men's Printed Regular fit T-Shirt Peopl...
4,unknown,unknown,1914.0,999999999,231.0,Monte Carlo Grey Solid Cotton Blend Polo Colla...

In [7]:
from app.services.text_encoder import (
    TextEncoder
)
from app.services.feature_builder import (
    FeatureBuilder
)

# Build structured features
builder = FeatureBuilder()

structured_features = (
    builder
    .build_structured_features(
        processed_df
    )
)

print(
    "Structured shape:",
    structured_features.shape
)

# Text embeddings
encoder = TextEncoder()

text_embeddings = encoder.encode(
    processed_df[
        "combined_text"
    ].tolist()[:100]
)

print(
    "Text embedding shape:",
    text_embeddings.shape
)

2026-05-28 18:58:35.089 | INFO     | app.services.text_encoder:__init__:22 - Loading model: sentence-transformers/all-MiniLM-L6-v2

Structured shape: (30000, 11019)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

2026-05-28 18:58:40.631 | INFO     | app.services.text_encoder:encode:35 - Encoding 100 products

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

Text embedding shape: (100, 384)

In [9]:
import numpy as np

In [10]:
text_embeddings = encoder.encode(
    processed_df[
        "combined_text"
    ].tolist()
)

structured_weight = 0.35
text_weight = 0.65

final_embeddings = np.hstack([
    structured_features
    * structured_weight,

    text_embeddings
    * text_weight
])

print(final_embeddings.shape)

2026-05-28 18:59:43.382 | INFO     | app.services.text_encoder:encode:35 - Encoding 30000 products

Batches:   0%|          | 0/469 [00:00<?, ?it/s]

(30000, 11403)

In [11]:
from app.services.similarity_engine import (
    SimilarityEngine
)

engine = SimilarityEngine(
    processed_df,
    final_embeddings
)

sample_product_id = (
    processed_df[
        "uniq_id"
    ].iloc[0]
)

similar_products = (
    engine.find_similar_products(
        product_id=sample_product_id,
        num_similar=5
    )
)

print(
    "Query Product:",
    sample_product_id
)

print(
    "Similar Products:"
)

similar_products

2026-05-28 19:00:31.893 | INFO     | app.services.faiss_index:build_index:21 - Building FAISS index
2026-05-28 19:00:34.160 | INFO     | app.services.faiss_index:build_index:50 - Indexed 30000 products

Query Product: 26d41bdc1495de290bc8e6062d927729
Similar Products:

['87cfe01c112f32fb0cb7e2b1354ce8a5',
 '8c1c7cfc44b7a5cbd38d47b506a58518',
 '1c93cbcd527aad73ae347dd6ac08d93c',
 '630cb8d7f5f66fc11dbd12631c269d36',
 'c8666212f128479ac11fa136778545a0']

In [12]:
query_product = processed_df[
    processed_df["uniq_id"]
    == sample_product_id
][[
    "product_name",
    "brand",
    "colour",
    "sales_price"
]]

query_product

,product_name,brand,colour,sales_price
0,LA' Facon Cotton Kalamkari Handblock Saree Blo...,la' facon,unknown,200.0

In [13]:
processed_df[
    processed_df["uniq_id"]
    .isin(similar_products)
][[
    "product_name",
    "brand",
    "colour",
    "sales_price"
]]

,product_name,brand,colour,sales_price
396,Pradeep Fashion Poly Cotton Stripe Style Saree...,pradeep fashion,unknown,199.0
1177,Pradeep Fashion Women's Cotton Silk Aura Aangi...,pradeep fashion,unknown,249.0
7720,Kerala cotton kasavu saree with golden border ...,generic,unknown,449.0
10577,Rofolo Women's Cotton Silk Saree with Blouse P...,rofolo,unknown,299.0
29180,Rahulraj Textile Women's Kalamkari Mysore Silk...,rahulraj textile,unknown,499.0

In [14]:
structured_weight = 0.45
text_weight = 0.55

final_embeddings = np.hstack([
    structured_features
    * structured_weight,

    text_embeddings
    * text_weight
])

In [15]:
engine = SimilarityEngine(
    processed_df,
    final_embeddings
)

2026-05-28 19:11:02.773 | INFO     | app.services.faiss_index:build_index:21 - Building FAISS index
2026-05-28 19:11:04.824 | INFO     | app.services.faiss_index:build_index:50 - Indexed 30000 products